### ISSUE TITLE
Add a section that shows the results of the parsing

### ISSUE THREAD

**Issue by firasnajjar** [Chevrotain/Chevrotain.github.io#6]
Think about how to show these results and what to show...

**Comment by bd82** [comment]
suggestion:

isString --> no conversion
isObject --> JSON.stringiy 
isNumber --> prolly autoConverted to string
isBoolean --> 'true' | 'false'

basically handle all the primitive types of javascript so it does not matter what a specific parser returns.

**Comment by bd82** [comment]
it won't work for custom objects though. we can do toSTring on those.
but how to separate plain javascript objects and "custom" ones?

**Comment by bd82** [comment]
https://lodash.com/docs#isPlainObject

**Comment by bd82** [comment]
for demo/playground purposes it is good enough to print toString/JSON.stringify
